// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "about": { "eyebrow": string; "heading": string; "body": string }; "clothing": { "eyebrow": string; "heading": string; "body": string }; "contact": { "eyebrow": string; "heading": string; "body": string }; "home": { "featuredProducts": Array<{ "id": string; "name": string; "subtitle": string; "desc": string; "price": string; "image": string }> }; "jewellery": { "eyebrow": string; "heading": string; "body": string }; "sarees": { "eyebrow": string; "heading": string; "body": string } };
  export const about: { "eyebrow": string; "heading": string; "body": string };
  export const clothing: { "eyebrow": string; "heading": string; "body": string };
  export const contact: { "eyebrow": string; "heading": string; "body": string };
  export const home: { "featuredProducts": Array<{ "id": string; "name": string; "subtitle": string; "desc": string; "price": string; "image": string }> };
  export const jewellery: { "eyebrow": string; "heading": string; "body": string };
  export const sarees: { "eyebrow": string; "heading": string; "body": string };
}
